exporter = "otlp"
processor = "batch"

[exporters.otlp]
# host and port are set via OTEL_EXPORTER_OTLP_ENDPOINT

[processors.batch]
max_queue_size = 2048
schedule_delay_millis = 5000
max_export_batch_size = 512
